name: graphula-persistent
version: "0.1.0"
maintainer: Front Row Education

extra-source-files:
  - ../stack.yaml

dependencies:
  - base
  - exceptions
  - graphula-core
  - mtl
  - persistent
  - QuickCheck
  - transformers
  - unliftio-core

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  readme:
    main: README.lhs
    ghc-options: -Wall -pgmL markdown-unlit
    dependencies:
      - aeson
      - base
      - graphula-persistent
      - hspec
      - markdown-unlit
      - monad-logger
      - persistent
      - persistent-arbitrary
      - persistent-template
      - persistent-sqlite
      - resourcet
