---
restylers:
  - brittany:
      image: restyled/restyler-brittany:v0.12.0.0
      include:
        - "**/*.hs"
  - stylish-haskell:
      include:
        - "**/*.hs"

comments: false

labels:
  - restyled
