name: graphula
version: 2.0.0.4
maintainer: Freckle Education
category: Network
github: freckle/graphula
synopsis: A declarative library for describing dependencies between data
description: Please see README.md

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  -Weverything
  -Wno-unsafe
  -Wno-safe
  -Wno-missing-import-lists
  -Wno-implicit-prelude

when:
  condition: impl(ghc >= 8.10)
  ghc-options:
    -Wno-missing-safe-haskell-mode
    -Wno-prepositive-qualified-module

dependencies:
  - base < 5

library:
  source-dirs:
    - src
  dependencies:
    - HUnit
    - QuickCheck < 2.15
    - containers
    - directory
    - generics-eot
    - mtl
    - persistent < 2.13
    - random < 1.3
    - semigroups
    - temporary
    - text
    - transformers
    - unliftio
    - unliftio-core < 0.3

tests:
  readme:
    main: README.lhs
    ghc-options: -pgmL markdown-unlit
    source-dirs:
      - test
    dependencies:
      - QuickCheck < 2.15
      - aeson < 1.6
      - bytestring < 0.12
      - containers
      - graphula
      - hspec
      - http-api-data
      - markdown-unlit
      - monad-logger
      - path-pieces
      - persistent < 2.13
      - persistent-sqlite < 2.13
      - persistent-template < 2.13
      - resourcet
      - text
      - transformers
      - unliftio-core < 0.3
      - uuid
