name: graphula
version: 2.0.0.1
maintainer: Freckle Education
category: Network
github: freckle/graphula
synopsis: A declarative library for describing dependencies between data
description: Please see README.md

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  -Weverything
  -Wno-unsafe
  -Wno-safe
  -Wno-missing-import-lists
  -Wno-implicit-prelude

dependencies:
  - base

library:
  source-dirs:
    - src
  dependencies:
    - HUnit
    - QuickCheck
    - containers
    - directory
    - generics-eot
    - mtl
    - persistent
    - random
    - semigroups
    - temporary
    - text
    - transformers
    - unliftio
    - unliftio-core

tests:
  readme:
    main: README.lhs
    ghc-options: -pgmL markdown-unlit
    source-dirs:
      - test
    dependencies:
      - QuickCheck
      - aeson
      - bytestring
      - containers
      - graphula
      - hspec
      - http-api-data
      - markdown-unlit
      - monad-logger
      - path-pieces
      - persistent
      - persistent-sqlite
      - persistent-template
      - resourcet
      - semigroups
      - text
      - transformers
      - unliftio-core
      - uuid
