resolver: lts-17.8

extra-deps:
  - generics-eot-0.4.0.1@sha256:3d8df1d8ca010238ec5f20ba30282daa0fac99c7de495fae64e26a7ea1dadb08,2312
  - lift-type-0.1.0.1
  - persistent-template-2.12.0.0
  - git: git@github.com:yesodweb/persistent
    commit: 315ae91349ef4fbc2f4f2595cb7d3423e79ef80f
    subdirs:
      - persistent
      - persistent-sqlite
      - persistent-mysql
      - persistent-postgresql

ghc-options:
  "$locals": -fwrite-ide-info
