version: 2.1

orbs:
  stack-build: pbrisbin/stack-build@4.0.0

workflows:
  commit:
    jobs:
      - stack-build/build-test-lint:
          name: build
      - stack-build/build-test-nightly:
          name: "nightly"

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - stack-build/build-test-nightly:
          name: "nightly"
