name: graphula-core
version: 1.0.0.0
maintainer: Freckle Education

extra-source-files:
  - ../stack.yaml

dependencies:
  - aeson
  - base
  - bytestring
  - containers
  - directory
  - exceptions
  - free
  - generics-eot
  - HUnit
  - mtl
  - persistent
  - QuickCheck
  - semigroups
  - temporary
  - transformers
  - unliftio
  - unliftio-core

library:
  source-dirs:
    - src
  ghc-options: -Wall

benchmarks:
  bench:
    source-dirs:
      - bench
    main: Main.hs
    ghc-options: -Wall -O2
    dependencies:
      - criterion
      - graphula-core
tests:
  readme:
    main: README.lhs
    ghc-options: -Wall -pgmL markdown-unlit
    source-dirs:
      - test
    dependencies:
      - base
      - graphula-core
      - hspec
      - http-api-data
      - markdown-unlit
      - monad-logger
      - path-pieces
      - persistent-arbitrary
      - persistent-sqlite
      - persistent-template
      - resourcet
      - text
      - uuid
