name: graphula-core
version: "0.3.0"
maintainer: Front Row Education

extra-source-files:
  - ../stack.yaml

dependencies:
  - aeson
  - base
  - bytestring
  - containers
  - directory
  - exceptions
  - free
  - generics-eot
  - HUnit
  - mtl
  - QuickCheck
  - temporary
  - transformers
  - unliftio
  - unliftio-core

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  readme:
    main: README.lhs
    ghc-options: -Wall -pgmL markdown-unlit
    dependencies:
      - base
      - graphula-core
      - hspec
      - markdown-unlit

benchmarks:
  bench:
    source-dirs:
      - bench
    main: Main.hs
    ghc-options: -Wall -O2
    dependencies:
      - criterion
      - graphula-core
