name: graphula-core
version: 2.0.0.0
maintainer: Freckle Education

extra-source-files:
  - ../stack.yaml

dependencies:
  - base

library:
  source-dirs:
    - src
  ghc-options: -Wall
  dependencies:
    - aeson
    - bytestring
    - containers
    - directory
    - generics-eot
    - HUnit
    - mtl
    - persistent
    - QuickCheck
    - semigroups
    - temporary
    - transformers
    - unliftio
    - unliftio-core

tests:
  readme:
    main: README.lhs
    ghc-options: -Wall -pgmL markdown-unlit
    source-dirs:
      - test
    dependencies:
      - aeson
      - bytestring
      - containers
      - graphula-core
      - hspec
      - http-api-data
      - markdown-unlit
      - monad-logger
      - path-pieces
      - persistent
      - persistent-arbitrary
      - persistent-sqlite
      - persistent-template
      - QuickCheck
      - resourcet
      - semigroups
      - text
      - transformers
      - unliftio-core
      - uuid
